grails-app/domain/ibs_lab1/Deposit.groovy
package ibs_lab1

class Deposit {

    static constraints = {
    }

    Counterparty counterparty
    DepositType depositType
    DepositInterestRateType interestRateType
    float depositAmount
    float interestRate
    int frequency   //цикличность начисления процентов (month)
    int depositTerm //(month)
    float result
}

grails-app/domain/ibs_lab1/DepositType.groovy
package ibs_lab1

class DepositType {

    static constraints = {
    }

    String alias
    String description
}

grails-app/controllers/ibs_lab1/DepositController.groovy
package ibs_lab1


import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class DepositController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond Deposit.list(params), model: [depositInstanceCount: Deposit.count()]
    }

    def show(Deposit depositInstance) {
        respond depositInstance
    }

    def create() {
        respond new Deposit(params)
    }

    @Transactional
    def save(Deposit depositInstance) {
        if (depositInstance == null) {
            notFound()
            return
        }

        if (depositInstance.hasErrors()) {
            respond depositInstance.errors, view: 'create'
            return
        }

        depositInstance.save flush: true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'deposit.label', default: 'Deposit'), depositInstance.id])
                redirect depositInstance
            }
            '*' { respond depositInstance, [status: CREATED] }
        }
    }

    def edit(Deposit depositInstance) {
        respond depositInstance
    }

    @Transactional
    def update(Deposit depositInstance) {
        if (depositInstance == null) {
            notFound()
            return
        }

        if (depositInstance.hasErrors()) {
            respond depositInstance.errors, view: 'edit'
            return
        }

        depositInstance.save flush: true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'Deposit.label', default: 'Deposit'), depositInstance.id])
                redirect depositInstance
            }
            '*' { respond depositInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(Deposit depositInstance) {

        if (depositInstance == null) {
            notFound()
            return
        }

        depositInstance.delete flush: true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'Deposit.label', default: 'Deposit'), depositInstance.id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'deposit.label', default: 'Deposit'), params.id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NOT_FOUND }
        }
    }
}

grails-app/views/deposit/_form.gsp
<%@ page import="ibs_lab1.DepositInterestRateType; ibs_lab1.InterestRateType; ibs_lab1.Deposit" %>



<div class="fieldcontain ${hasErrors(bean: depositInstance, field: 'counterparty', 'error')} required">
    <label for="counterparty">
        <g:message code="deposit.counterparty.label" default="Counterparty"/>
        <span class="required-indicator">*</span>
    </label>
    <g:select id="counterparty" name="counterparty.id" from="${ibs_lab1.Counterparty.list()}" optionKey="id" required=""
              value="${depositInstance?.counterparty?.id}" class="many-to-one"/>

</div>

<div class="fieldcontain ${hasErrors(bean: depositInstance, field: 'depositAmount', 'error')} required">
    <label for="depositAmount">
        <g:message code="deposit.depositAmount.label" default="Deposit Amount"/>
        <span class="required-indicator">*</span>
    </label>
    <g:field name="depositAmount" value="${fieldValue(bean: depositInstance, field: 'depositAmount')}" required=""/>

</div>

<div class="fieldcontain ${hasErrors(bean: depositInstance, field: 'depositTerm', 'error')} required">
    <label for="depositTerm">
        <g:message code="deposit.depositTerm.label" default="Deposit Term"/>
        <span class="required-indicator">*</span>
    </label>
    <g:field name="depositTerm" type="number" value="${depositInstance.depositTerm}" required=""/>

</div>

<div class="fieldcontain ${hasErrors(bean: depositInstance, field: 'depositType', 'error')} required">
    <label for="depositType">
        <g:message code="deposit.depositType.label" default="Deposit Type"/>
        <span class="required-indicator">*</span>
    </label>
    <g:select id="depositType" name="depositType.id" from="${ibs_lab1.DepositType.list()}" optionKey="id" required=""
              value="${depositInstance?.depositType?.id}" class="many-to-one"/>

</div>

<div class="fieldcontain ${hasErrors(bean: depositInstance, field: 'frequency', 'error')} required">
    <label for="frequency">
        <g:message code="deposit.frequency.label" default="Frequency"/>
        <span class="required-indicator">*</span>
    </label>
    <g:field name="frequency" type="number" value="${depositInstance.frequency}" required=""/>

</div>

<div class="fieldcontain ${hasErrors(bean: depositInstance, field: 'interestRate', 'error')} required">
    <label for="interestRate">
        <g:message code="deposit.interestRate.label" default="Interest Rate"/>
        <span class="required-indicator">*</span>
    </label>
    <g:field name="interestRate" value="${fieldValue(bean: depositInstance, field: 'interestRate')}" required=""/>

</div>

<div class="fieldcontain ${hasErrors(bean: depositInstance, field: 'interestRateType', 'error')} required">
    <label for="interestType">
        <g:message code="deposit.interestType.label" default="Interest Type"/>
        <span class="required-indicator">*</span>
    </label>
    <g:select id="interestType" name="interestType.id" from="${ibs_lab1.DepositInterestRateType.list()}" optionKey="id" required=""
              value="${depositInstance?.interestType?.id}" class="many-to-one"/>

</div>

grails-app/views/deposit/create.gsp
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main">
    <g:set var="entityName" value="${message(code: 'deposit.label', default: 'Deposit')}"/>
    <title><g:message code="default.create.label" args="[entityName]"/></title>
</head>

<body>
<a href="#create-deposit" class="skip" tabindex="-1"><g:message code="default.link.skip.label"
                                                                default="Skip to content&hellip;"/></a>

<div class="nav" role="navigation">
    <ul>
        <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
        <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]"/></g:link></li>
    </ul>
</div>

<div id="create-deposit" class="content scaffold-create" role="main">
    <h1><g:message code="default.create.label" args="[entityName]"/></h1>
    <g:if test="${flash.message}">
        <div class="message" role="status">${flash.message}</div>
    </g:if>
    <g:hasErrors bean="${depositInstance}">
        <ul class="errors" role="alert">
            <g:eachError bean="${depositInstance}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message
                        error="${error}"/></li>
            </g:eachError>
        </ul>
    </g:hasErrors>
    <g:form url="[resource: depositInstance, action: 'save']">
        <fieldset class="form">
            <g:render template="form"/>
        </fieldset>
        <fieldset class="buttons">
            <g:submitButton name="create" class="save"
                            value="${message(code: 'default.button.create.label', default: 'Create')}"/>
        </fieldset>
    </g:form>
</div>
</body>
</html>

grails-app/views/deposit/edit.gsp
<%@ page import="ibs_lab1.Deposit" %>
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main">
    <g:set var="entityName" value="${message(code: 'deposit.label', default: 'Deposit')}"/>
    <title><g:message code="default.edit.label" args="[entityName]"/></title>
</head>

<body>
<a href="#edit-deposit" class="skip" tabindex="-1"><g:message code="default.link.skip.label"
                                                              default="Skip to content&hellip;"/></a>

<div class="nav" role="navigation">
    <ul>
        <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
        <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]"/></g:link></li>
        <li><g:link class="create" action="create"><g:message code="default.new.label"
                                                              args="[entityName]"/></g:link></li>
    </ul>
</div>

<div id="edit-deposit" class="content scaffold-edit" role="main">
    <h1><g:message code="default.edit.label" args="[entityName]"/></h1>
    <g:if test="${flash.message}">
        <div class="message" role="status">${flash.message}</div>
    </g:if>
    <g:hasErrors bean="${depositInstance}">
        <ul class="errors" role="alert">
            <g:eachError bean="${depositInstance}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message
                        error="${error}"/></li>
            </g:eachError>
        </ul>
    </g:hasErrors>
    <g:form url="[resource: depositInstance, action: 'update']" method="PUT">
        <g:hiddenField name="version" value="${depositInstance?.version}"/>
        <fieldset class="form">
            <g:render template="form"/>
        </fieldset>
        <fieldset class="buttons">
            <g:actionSubmit class="save" action="update"
                            value="${message(code: 'default.button.update.label', default: 'Update')}"/>
        </fieldset>
    </g:form>
</div>
</body>
</html>

grails-app/views/deposit/index.gsp
<%@ page import="ibs_lab1.Deposit" %>
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main">
    <g:set var="entityName" value="${message(code: 'deposit.label', default: 'Deposit')}"/>
    <title><g:message code="default.list.label" args="[entityName]"/></title>
</head>

<body>
<a href="#list-deposit" class="skip" tabindex="-1"><g:message code="default.link.skip.label"
                                                              default="Skip to content&hellip;"/></a>

<div class="nav" role="navigation">
    <ul>
        <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
        <li><g:link class="create" action="create"><g:message code="default.new.label"
                                                              args="[entityName]"/></g:link></li>
    </ul>
</div>

<div id="list-deposit" class="content scaffold-list" role="main">
    <h1><g:message code="default.list.label" args="[entityName]"/></h1>
    <g:if test="${flash.message}">
        <div class="message" role="status">${flash.message}</div>
    </g:if>
    <table>
        <thead>
        <tr>

            <th><g:message code="deposit.counterparty.label" default="Counterparty"/></th>

            <g:sortableColumn property="depositAmount"
                              title="${message(code: 'deposit.depositAmount.label', default: 'Deposit Amount')}"/>

            <g:sortableColumn property="depositTerm"
                              title="${message(code: 'deposit.depositTerm.label', default: 'Deposit Term')}"/>

            <th><g:message code="deposit.depositType.label" default="Deposit Type"/></th>

            <g:sortableColumn property="frequency"
                              title="${message(code: 'deposit.frequency.label', default: 'Frequency')}"/>

            <g:sortableColumn property="interestRate"
                              title="${message(code: 'deposit.interestRate.label', default: 'Interest Rate')}"/>

        </tr>
        </thead>
        <tbody>
        <g:each in="${depositInstanceList}" status="i" var="depositInstance">
            <tr class="${(i % 2) == 0 ? 'even' : 'odd'}">

                <td><g:link action="show" id="${depositInstance.id}">
                    ${fieldValue(bean: depositInstance.counterparty, field: "userName")}
                </g:link></td>
                <td>${fieldValue(bean: depositInstance, field: "depositAmount")}</td>
                <td>${fieldValue(bean: depositInstance, field: "depositTerm")}</td>
                <td>${fieldValue(bean: depositInstance.depositType, field: "alias")}</td>
                <td>${fieldValue(bean: depositInstance, field: "interestRate")}</td>
                <td>${fieldValue(bean: depositInstance, field: "frequency")}</td>

            </tr>
        </g:each>
        </tbody>
    </table>

    <div class="pagination">
        <g:paginate total="${depositInstanceCount ?: 0}"/>
    </div>
</div>
</body>
</html>

grails-app/views/deposit/show.gsp
<%@ page import="ibs_lab1.Deposit" %>
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main">
    <g:set var="entityName" value="${message(code: 'deposit.label', default: 'Deposit')}"/>
    <title><g:message code="default.show.label" args="[entityName]"/></title>
</head>

<body>
<a href="#show-deposit" class="skip" tabindex="-1"><g:message code="default.link.skip.label"
                                                              default="Skip to content&hellip;"/></a>

<div class="nav" role="navigation">
    <ul>
        <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
        <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]"/></g:link></li>
        <li><g:link class="create" action="create"><g:message code="default.new.label"
                                                              args="[entityName]"/></g:link></li>
    </ul>
</div>

<div id="show-deposit" class="content scaffold-show" role="main">
    <h1><g:message code="default.show.label" args="[entityName]"/></h1>
    <g:if test="${flash.message}">
        <div class="message" role="status">${flash.message}</div>
    </g:if>
    <ol class="property-list deposit">

        <g:if test="${depositInstance?.counterparty}">
            <li class="fieldcontain">
                <span id="counterparty-label" class="property-label"><g:message code="deposit.counterparty.label"
                                                                                default="Counterparty"/></span>

                <span class="property-value" aria-labelledby="counterparty-label"><g:link controller="counterparty"
                                                                                          action="show"
                                                                                          id="${depositInstance?.counterparty?.id}">${depositInstance?.counterparty?.encodeAsHTML()}</g:link></span>

            </li>
        </g:if>

        <g:if test="${depositInstance?.depositAmount}">
            <li class="fieldcontain">
                <span id="depositAmount-label" class="property-label"><g:message code="deposit.depositAmount.label"
                                                                                 default="Deposit Amount"/></span>

                <span class="property-value" aria-labelledby="depositAmount-label"><g:fieldValue
                        bean="${depositInstance}" field="depositAmount"/></span>

            </li>
        </g:if>

        <g:if test="${depositInstance?.depositTerm}">
            <li class="fieldcontain">
                <span id="depositTerm-label" class="property-label"><g:message code="deposit.depositTerm.label"
                                                                               default="Deposit Term"/></span>

                <span class="property-value" aria-labelledby="depositTerm-label"><g:fieldValue bean="${depositInstance}"
                                                                                               field="depositTerm"/></span>

            </li>
        </g:if>

        <g:if test="${depositInstance?.depositType}">
            <li class="fieldcontain">
                <span id="depositType-label" class="property-label"><g:message code="deposit.depositType.label"
                                                                               default="Deposit Type"/></span>

                <span class="property-value" aria-labelledby="depositType-label"><g:link controller="depositType"
                                                                                         action="show"
                                                                                         id="${depositInstance?.depositType?.id}">${depositInstance?.depositType?.encodeAsHTML()}</g:link></span>

            </li>
        </g:if>

        <g:if test="${depositInstance?.frequency}">
            <li class="fieldcontain">
                <span id="frequency-label" class="property-label"><g:message code="deposit.frequency.label"
                                                                             default="Frequency"/></span>

                <span class="property-value" aria-labelledby="frequency-label"><g:fieldValue bean="${depositInstance}"
                                                                                             field="frequency"/></span>

            </li>
        </g:if>

        <g:if test="${depositInstance?.interestRate}">
            <li class="fieldcontain">
                <span id="interestRate-label" class="property-label"><g:message code="deposit.interestRate.label"
                                                                                default="Interest Rate"/></span>

                <span class="property-value" aria-labelledby="interestRate-label"><g:fieldValue
                        bean="${depositInstance}" field="interestRate"/></span>

            </li>
        </g:if>

        <g:if test="${depositInstance?.interestType}">
            <li class="fieldcontain">
                <span id="interestType-label" class="property-label"><g:message code="deposit.interestType.label"
                                                                                default="Interest Type"/></span>

                <span class="property-value" aria-labelledby="interestType-label"><g:link controller="interestType"
                                                                                          action="show"
                                                                                          id="${depositInstance?.interestType?.id}">${depositInstance?.interestType?.encodeAsHTML()}</g:link></span>

            </li>
        </g:if>

    </ol>
    <g:form url="[resource: depositInstance, action: 'delete']" method="DELETE">
        <fieldset class="buttons">
            <g:link class="edit" action="edit" resource="${depositInstance}"><g:message code="default.button.edit.label"
                                                                                        default="Edit"/></g:link>
            <g:actionSubmit class="delete" action="delete"
                            value="${message(code: 'default.button.delete.label', default: 'Delete')}"
                            onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');"/>
        </fieldset>
    </g:form>
</div>
</body>
</html>