grails-app/controllers/ibs_lab1/DepositInterestRateTypeController.groovy
package ibs_lab1


import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class DepositInterestRateTypeController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond DepositInterestRateType.list(params), model: [depositInterestRateTypeInstanceCount: DepositInterestRateType.count()]
    }

    def show(DepositInterestRateType depositInterestRateTypeInstance) {
        respond depositInterestRateTypeInstance
    }

    def create() {
        respond new DepositInterestRateType(params)
    }

    @Transactional
    def save(DepositInterestRateType depositInterestRateTypeInstance) {
        if (depositInterestRateTypeInstance == null) {
            notFound()
            return
        }

        if (depositInterestRateTypeInstance.hasErrors()) {
            respond depositInterestRateTypeInstance.errors, view: 'create'
            return
        }

        depositInterestRateTypeInstance.save flush: true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'depositInterestRateType.label', default: 'DepositInterestRateType'), depositInterestRateTypeInstance.id])
                redirect depositInterestRateTypeInstance
            }
            '*' { respond depositInterestRateTypeInstance, [status: CREATED] }
        }
    }

    def edit(DepositInterestRateType depositInterestRateTypeInstance) {
        respond depositInterestRateTypeInstance
    }

    @Transactional
    def update(DepositInterestRateType depositInterestRateTypeInstance) {
        if (depositInterestRateTypeInstance == null) {
            notFound()
            return
        }

        if (depositInterestRateTypeInstance.hasErrors()) {
            respond depositInterestRateTypeInstance.errors, view: 'edit'
            return
        }

        depositInterestRateTypeInstance.save flush: true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'DepositInterestRateType.label', default: 'DepositInterestRateType'), depositInterestRateTypeInstance.id])
                redirect depositInterestRateTypeInstance
            }
            '*' { respond depositInterestRateTypeInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(DepositInterestRateType depositInterestRateTypeInstance) {

        if (depositInterestRateTypeInstance == null) {
            notFound()
            return
        }

        depositInterestRateTypeInstance.delete flush: true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'DepositInterestRateType.label', default: 'DepositInterestRateType'), depositInterestRateTypeInstance.id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'depositInterestRateType.label', default: 'DepositInterestRateType'), params.id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NOT_FOUND }
        }
    }
}

grails-app/views/depositInterestRateType/_form.gsp
<%@ page import="ibs_lab1.DepositInterestRateType" %>



<div class="fieldcontain ${hasErrors(bean: depositInterestRateTypeInstance, field: 'alias', 'error')} required">
	<label for="alias">
		<g:message code="depositInterestRateType.alias.label" default="Alias" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="alias" required="" value="${depositInterestRateTypeInstance?.alias}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: depositInterestRateTypeInstance, field: 'description', 'error')} required">
	<label for="description">
		<g:message code="depositInterestRateType.description.label" default="Description" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="description" required="" value="${depositInterestRateTypeInstance?.description}"/>

</div>

grails-app/views/depositInterestRateType/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'depositInterestRateType.label', default: 'DepositInterestRateType')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-depositInterestRateType" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-depositInterestRateType" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${depositInterestRateTypeInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${depositInterestRateTypeInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:depositInterestRateTypeInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/depositInterestRateType/edit.gsp
<%@ page import="ibs_lab1.DepositInterestRateType" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'depositInterestRateType.label', default: 'DepositInterestRateType')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-depositInterestRateType" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-depositInterestRateType" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${depositInterestRateTypeInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${depositInterestRateTypeInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:depositInterestRateTypeInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${depositInterestRateTypeInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/depositInterestRateType/index.gsp
<%@ page import="ibs_lab1.DepositInterestRateType" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'depositInterestRateType.label', default: 'DepositInterestRateType')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-depositInterestRateType" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-depositInterestRateType" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<g:sortableColumn property="alias" title="${message(code: 'depositInterestRateType.alias.label', default: 'Alias')}" />
					
						<g:sortableColumn property="description" title="${message(code: 'depositInterestRateType.description.label', default: 'Description')}" />
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${depositInterestRateTypeInstanceList}" status="i" var="depositInterestRateTypeInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${depositInterestRateTypeInstance.id}">${fieldValue(bean: depositInterestRateTypeInstance, field: "alias")}</g:link></td>
					
						<td>${fieldValue(bean: depositInterestRateTypeInstance, field: "description")}</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${depositInterestRateTypeInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/depositInterestRateType/show.gsp
<%@ page import="ibs_lab1.DepositInterestRateType" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'depositInterestRateType.label', default: 'DepositInterestRateType')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-depositInterestRateType" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-depositInterestRateType" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list depositInterestRateType">
			
				<g:if test="${depositInterestRateTypeInstance?.alias}">
				<li class="fieldcontain">
					<span id="alias-label" class="property-label"><g:message code="depositInterestRateType.alias.label" default="Alias" /></span>
					
						<span class="property-value" aria-labelledby="alias-label"><g:fieldValue bean="${depositInterestRateTypeInstance}" field="alias"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${depositInterestRateTypeInstance?.description}">
				<li class="fieldcontain">
					<span id="description-label" class="property-label"><g:message code="depositInterestRateType.description.label" default="Description" /></span>
					
						<span class="property-value" aria-labelledby="description-label"><g:fieldValue bean="${depositInterestRateTypeInstance}" field="description"/></span>
					
				</li>
				</g:if>
			
			</ol>
			<g:form url="[resource:depositInterestRateTypeInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${depositInterestRateTypeInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>