grails-app/domain/ibs_lab1/Credit.groovy
package ibs_lab1

class Credit {

    static constraints = {
    }

    Counterparty counterparty
    int loanAmount
    int numberOfMonth
    float interestRate
    Date dateCreated
    Date lastUpdated
    CreditProgram creditProgram
    float finalResult
    float payAmount
}

grails-app/controllers/ibs_lab1/CreditController.groovy
package ibs_lab1

import beans.CreditBean
import grails.transaction.Transactional

import static org.springframework.http.HttpStatus.*

@Transactional(readOnly = true)
class CreditController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond Credit.list(params), model: [creditInstanceCount: Credit.count()]
    }

    def show(Credit creditInstance) {
        respond creditInstance
    }

    def create() {
        respond new Credit(params)
    }

    def calculate(Credit credit) {
        def loanAmount = credit.loanAmount
        List<CreditBean> beans = new ArrayList<>()
        def totalPaidRaid = 0
        if (credit.creditProgram.programAlias == 'Program #1') {
            def payAmount = credit.payAmount
            def numberOfMonth = loanAmount / payAmount
            numberOfMonth.times {
                loanAmount -= payAmount
                payAmount = payAmount > loanAmount ? loanAmount : payAmount
                def paidRaid = loanAmount * credit.interestRate / 100
                totalPaidRaid += paidRaid
                beans.add(new CreditBean(
                        left: loanAmount,
                        paid: payAmount,
                        paidRaid: paidRaid
                ))
            }
        } else if (credit.creditProgram.programAlias == 'Program #2') {
            def payAmount = loanAmount / credit.numberOfMonth
            def number = credit.numberOfMonth - 1
            number.times {
                loanAmount -= payAmount
                payAmount = payAmount > loanAmount ? loanAmount : payAmount
                def paidRaid = loanAmount * credit.interestRate / 100
                totalPaidRaid += paidRaid
                beans.add(new CreditBean(
                        left: loanAmount,
                        paid: payAmount,
                        paidRaid: paidRaid
                ))
            }
        }

        render(view: "calculate", model: [
                beans: beans,
                totalPaidRaid: Math.round(totalPaidRaid * 100) / 100
        ])
    }

    @Transactional
    def save(Credit creditInstance) {
        if (creditInstance == null) {
            notFound()
            return
        }

        if (creditInstance.hasErrors()) {
            respond creditInstance.errors, view: 'create'
            return
        }

        creditInstance.save flush: true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'credit.label', default: 'Credit'), creditInstance.id])
                redirect creditInstance
            }
            '*' { respond creditInstance, [status: CREATED] }
        }
    }

    def edit(Credit creditInstance) {
        respond creditInstance
    }

    @Transactional
    def update(Credit creditInstance) {
        if (creditInstance == null) {
            notFound()
            return
        }

        if (creditInstance.hasErrors()) {
            respond creditInstance.errors, view: 'edit'
            return
        }

        creditInstance.save flush: true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'Credit.label', default: 'Credit'), creditInstance.id])
                redirect creditInstance
            }
            '*' { respond creditInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(Credit creditInstance) {

        if (creditInstance == null) {
            notFound()
            return
        }

        creditInstance.delete flush: true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'Credit.label', default: 'Credit'), creditInstance.id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'credit.label', default: 'Credit'), params.id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NOT_FOUND }
        }
    }
}

grails-app/views/credit/_form.gsp
<%@ page import="ibs_lab1.Credit" %>



<div class="fieldcontain ${hasErrors(bean: creditInstance, field: 'counterparty', 'error')} required">
	<label for="counterparty">
		<g:message code="credit.counterparty.label" default="Counterparty" />
		<span class="required-indicator">*</span>
	</label>
	<g:select id="counterparty" name="counterparty.id" from="${ibs_lab1.Counterparty.list()}" optionKey="id" required=""
			  value="${creditInstance?.counterparty?.id}" class="many-to-one" optionValue="userName"/>

</div>

<div class="fieldcontain ${hasErrors(bean: creditInstance, field: 'creditProgram', 'error')} required">
	<label for="creditProgram">
		<g:message code="credit.creditProgram.label" default="Credit Program" />
		<span class="required-indicator">*</span>
	</label>
	<g:select id="creditProgram" name="creditProgram.id" from="${ibs_lab1.CreditProgram.list()}" optionKey="id" required=""
			  value="${creditInstance?.creditProgram?.id}" class="many-to-one" optionValue="programAlias"/>

</div>

<div class="fieldcontain ${hasErrors(bean: creditInstance, field: 'interestRate', 'error')} required">
	<label for="interestRate">
		<g:message code="credit.interestRate.label" default="Interest Rate" />
		<span class="required-indicator">*</span>
	</label>
	<g:field name="interestRate" value="${fieldValue(bean: creditInstance, field: 'interestRate')}" required=""/>

</div>

<div class="fieldcontain ${hasErrors(bean: creditInstance, field: 'loanAmount', 'error')} required">
	<label for="loanAmount">
		<g:message code="credit.loanAmount.label" default="Loan Amount" />
		<span class="required-indicator">*</span>
	</label>
	<g:field name="loanAmount" type="number" value="${creditInstance.loanAmount}" required=""/>

</div>

<g:if test="${creditInstance?.creditProgram.programAlias == 'Program #1'}">
	<div class="fieldcontain ${hasErrors(bean: creditInstance, field: 'payAmount', 'error')} required">
	<label for="payAmount">
		<g:message code="credit.numberOfMonth.label" default="Pay Amount" />
		<span class="required-indicator">*</span>
	</label>
	<g:field name="payAmount" type="number" value="${creditInstance.payAmount}" required=""/>
</g:if>

</div>

grails-app/views/credit/calculate.gsp
<%@ page import="ibs_lab1.Credit" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'credit.label', default: 'Credit')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-credit" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-credit" class="content scaffold-list" role="main">
			<h1>Credit Calculator</h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
						<th style="width: 50px;"><g:message code="credit.counterparty.label" default="Місяць" /></th>
						<th><g:message code="credit.counterparty.label" default="Залишок" /></th>
						<th><g:message code="credit.creditProgram.label" default="Оплата" /></th>
						<th><g:message code="credit.creditProgram.label" default="Оплата відсотків" /></th>
					</tr>
				</thead>
				<tbody>
				<g:each in="${beans}" status="i" var="bean">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
						<td>${i}</td>
						<td>${bean.left}</td>
						<td>${bean.paid}</td>
						<td>${bean.paidRaid}</td>
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${creditInstanceCount ?: 0}" />
			</div>
			<h3 style="padding: 15px 0 0 30px">Сума оплачених відсотків = ${totalPaidRaid}</h3>
		</div>
	</body>
</html>

grails-app/views/credit/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'credit.label', default: 'Credit')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-credit" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-credit" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${creditInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${creditInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:creditInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/credit/edit.gsp
<%@ page import="ibs_lab1.Credit" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'credit.label', default: 'Credit')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-credit" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-credit" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${creditInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${creditInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:creditInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${creditInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/credit/index.gsp
<%@ page import="ibs_lab1.Credit" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'credit.label', default: 'Credit')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-credit" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-credit" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
						<th><g:message code="credit.counterparty.label" default="Counterparty" /></th>
						<th><g:message code="credit.creditProgram.label" default="Credit Program" /></th>
						<g:sortableColumn property="dateCreated" title="${message(code: 'credit.dateCreated.label', default: 'Date Created')}" />
						<g:sortableColumn property="interestRate" title="${message(code: 'credit.interestRate.label', default: 'Interest Rate')}" />
						<g:sortableColumn property="lastUpdated" title="${message(code: 'credit.lastUpdated.label', default: 'Number of month')}" />
						<g:sortableColumn property="loanAmount" title="${message(code: 'credit.loanAmount.label', default: 'Loan Amount')}" />
					</tr>
				</thead>
				<tbody>
				<g:each in="${creditInstanceList}" status="i" var="creditInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
						<td><g:link action="show" id="${creditInstance.id}">
							${fieldValue(bean: creditInstance.counterparty, field: "userName")}
						</g:link></td>
						<td>${fieldValue(bean: creditInstance.creditProgram, field: "programAlias")}</td>
						<td><g:formatDate date="${creditInstance.dateCreated}" /></td>
						<td>${fieldValue(bean: creditInstance, field: "interestRate")}</td>
						<td>${fieldValue(bean: creditInstance, field: "numberOfMonth")}</td>
						<td>${fieldValue(bean: creditInstance, field: "loanAmount")}</td>
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${creditInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/credit/show.gsp
<%@ page import="ibs_lab1.Credit" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'credit.label', default: 'Credit')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-credit" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-credit" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list credit">
			
				<g:if test="${creditInstance?.counterparty}">
				<li class="fieldcontain">
					<span id="counterparty-label" class="property-label"><g:message code="credit.counterparty.label" default="Counterparty" /></span>
						<span class="property-value" aria-labelledby="counterparty-label">
							<g:link controller="counterparty" action="show" id="${creditInstance?.counterparty?.id}">
								${creditInstance?.counterparty?.userName}
							</g:link>
						</span>
				</li>
				</g:if>
			
				<g:if test="${creditInstance?.creditProgram}">
				<li class="fieldcontain">
					<span id="creditProgram-label" class="property-label"><g:message code="credit.creditProgram.label" default="Credit Program" /></span>
						<span class="property-value" aria-labelledby="creditProgram-label">
							<g:link controller="creditProgram" action="show" id="${creditInstance?.creditProgram?.id}">
								${creditInstance?.creditProgram?.programAlias}
							</g:link>
						</span>
					
				</li>
				</g:if>
			
				<g:if test="${creditInstance?.dateCreated}">
				<li class="fieldcontain">
					<span id="dateCreated-label" class="property-label"><g:message code="credit.dateCreated.label" default="Date Created" /></span>
					
						<span class="property-value" aria-labelledby="dateCreated-label"><g:formatDate date="${creditInstance?.dateCreated}" /></span>
					
				</li>
				</g:if>
			
				<g:if test="${creditInstance?.interestRate}">
				<li class="fieldcontain">
					<span id="interestRate-label" class="property-label"><g:message code="credit.interestRate.label" default="Interest Rate" /></span>
					
						<span class="property-value" aria-labelledby="interestRate-label"><g:fieldValue bean="${creditInstance}" field="interestRate"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${creditInstance?.lastUpdated}">
				<li class="fieldcontain">
					<span id="lastUpdated-label" class="property-label"><g:message code="credit.lastUpdated.label" default="Last Updated" /></span>
					
						<span class="property-value" aria-labelledby="lastUpdated-label"><g:formatDate date="${creditInstance?.lastUpdated}" /></span>
					
				</li>
				</g:if>
			
				<g:if test="${creditInstance?.loanAmount}">
				<li class="fieldcontain">
					<span id="loanAmount-label" class="property-label"><g:message code="credit.loanAmount.label" default="Loan Amount" /></span>
					
						<span class="property-value" aria-labelledby="loanAmount-label"><g:fieldValue bean="${creditInstance}" field="loanAmount"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${creditInstance?.numberOfMonth}">
				<li class="fieldcontain">
					<span id="numberOfMonth-label" class="property-label"><g:message code="credit.numberOfMonth.label" default="Number Of Month" /></span>
						<span class="property-value" aria-labelledby="numberOfMonth-label"><g:fieldValue bean="${creditInstance}" field="numberOfMonth"/></span>
				</li>
				</g:if>
				<g:if test="${creditInstance?.creditProgram.programAlias == 'Program #1'}">
					<li class="fieldcontain">
						<span id="payAmount-label" class="property-label"><g:message code="credit.numberOfMonth.label" default="Pay Amount" /></span>
						<span class="property-value" aria-labelledby="payAmount-label"><g:fieldValue bean="${creditInstance}" field="payAmount"/></span>
					</li>
				</g:if>
			
			</ol>
			<g:form url="[resource:creditInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${creditInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
					<g:link  action="calculate" resource="${creditInstance}"><g:message code="default.button.calculate.label" default="Calculate" /></g:link>
				</fieldset>
			</g:form>
		</div>
	</body>
</html>