grails-app/controllers/ibs_lab1/DepositTypeController.groovy
package ibs_lab1


import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class DepositTypeController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond DepositType.list(params), model: [depositTypeInstanceCount: DepositType.count()]
    }

    def show(DepositType depositTypeInstance) {
        respond depositTypeInstance
    }

    def create() {
        respond new DepositType(params)
    }

    @Transactional
    def save(DepositType depositTypeInstance) {
        if (depositTypeInstance == null) {
            notFound()
            return
        }

        if (depositTypeInstance.hasErrors()) {
            respond depositTypeInstance.errors, view: 'create'
            return
        }

        depositTypeInstance.save flush: true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'depositType.label', default: 'DepositType'), depositTypeInstance.id])
                redirect depositTypeInstance
            }
            '*' { respond depositTypeInstance, [status: CREATED] }
        }
    }

    def edit(DepositType depositTypeInstance) {
        respond depositTypeInstance
    }

    @Transactional
    def update(DepositType depositTypeInstance) {
        if (depositTypeInstance == null) {
            notFound()
            return
        }

        if (depositTypeInstance.hasErrors()) {
            respond depositTypeInstance.errors, view: 'edit'
            return
        }

        depositTypeInstance.save flush: true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'DepositType.label', default: 'DepositType'), depositTypeInstance.id])
                redirect depositTypeInstance
            }
            '*' { respond depositTypeInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(DepositType depositTypeInstance) {

        if (depositTypeInstance == null) {
            notFound()
            return
        }

        depositTypeInstance.delete flush: true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'DepositType.label', default: 'DepositType'), depositTypeInstance.id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'depositType.label', default: 'DepositType'), params.id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NOT_FOUND }
        }
    }
}

grails-app/views/depositType/_form.gsp
<%@ page import="ibs_lab1.DepositType" %>



<div class="fieldcontain ${hasErrors(bean: depositTypeInstance, field: 'alias', 'error')} required">
    <label for="alias">
        <g:message code="depositType.alias.label" default="Alias"/>
        <span class="required-indicator">*</span>
    </label>
    <g:textField name="alias" required="" value="${depositTypeInstance?.alias}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: depositTypeInstance, field: 'description', 'error')} required">
    <label for="description">
        <g:message code="depositType.description.label" default="Description"/>
        <span class="required-indicator">*</span>
    </label>
    <g:textField name="description" required="" value="${depositTypeInstance?.description}"/>

</div>

grails-app/views/depositType/create.gsp
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main">
    <g:set var="entityName" value="${message(code: 'depositType.label', default: 'DepositType')}"/>
    <title><g:message code="default.create.label" args="[entityName]"/></title>
</head>

<body>
<a href="#create-depositType" class="skip" tabindex="-1"><g:message code="default.link.skip.label"
                                                                    default="Skip to content&hellip;"/></a>

<div class="nav" role="navigation">
    <ul>
        <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
        <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]"/></g:link></li>
    </ul>
</div>

<div id="create-depositType" class="content scaffold-create" role="main">
    <h1><g:message code="default.create.label" args="[entityName]"/></h1>
    <g:if test="${flash.message}">
        <div class="message" role="status">${flash.message}</div>
    </g:if>
    <g:hasErrors bean="${depositTypeInstance}">
        <ul class="errors" role="alert">
            <g:eachError bean="${depositTypeInstance}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message
                        error="${error}"/></li>
            </g:eachError>
        </ul>
    </g:hasErrors>
    <g:form url="[resource: depositTypeInstance, action: 'save']">
        <fieldset class="form">
            <g:render template="form"/>
        </fieldset>
        <fieldset class="buttons">
            <g:submitButton name="create" class="save"
                            value="${message(code: 'default.button.create.label', default: 'Create')}"/>
        </fieldset>
    </g:form>
</div>
</body>
</html>

grails-app/views/depositType/edit.gsp
<%@ page import="ibs_lab1.DepositType" %>
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main">
    <g:set var="entityName" value="${message(code: 'depositType.label', default: 'DepositType')}"/>
    <title><g:message code="default.edit.label" args="[entityName]"/></title>
</head>

<body>
<a href="#edit-depositType" class="skip" tabindex="-1"><g:message code="default.link.skip.label"
                                                                  default="Skip to content&hellip;"/></a>

<div class="nav" role="navigation">
    <ul>
        <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
        <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]"/></g:link></li>
        <li><g:link class="create" action="create"><g:message code="default.new.label"
                                                              args="[entityName]"/></g:link></li>
    </ul>
</div>

<div id="edit-depositType" class="content scaffold-edit" role="main">
    <h1><g:message code="default.edit.label" args="[entityName]"/></h1>
    <g:if test="${flash.message}">
        <div class="message" role="status">${flash.message}</div>
    </g:if>
    <g:hasErrors bean="${depositTypeInstance}">
        <ul class="errors" role="alert">
            <g:eachError bean="${depositTypeInstance}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message
                        error="${error}"/></li>
            </g:eachError>
        </ul>
    </g:hasErrors>
    <g:form url="[resource: depositTypeInstance, action: 'update']" method="PUT">
        <g:hiddenField name="version" value="${depositTypeInstance?.version}"/>
        <fieldset class="form">
            <g:render template="form"/>
        </fieldset>
        <fieldset class="buttons">
            <g:actionSubmit class="save" action="update"
                            value="${message(code: 'default.button.update.label', default: 'Update')}"/>
        </fieldset>
    </g:form>
</div>
</body>
</html>

grails-app/views/depositType/index.gsp
<%@ page import="ibs_lab1.DepositType" %>
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main">
    <g:set var="entityName" value="${message(code: 'depositType.label', default: 'DepositType')}"/>
    <title><g:message code="default.list.label" args="[entityName]"/></title>
</head>

<body>
<a href="#list-depositType" class="skip" tabindex="-1"><g:message code="default.link.skip.label"
                                                                  default="Skip to content&hellip;"/></a>

<div class="nav" role="navigation">
    <ul>
        <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
        <li><g:link class="create" action="create"><g:message code="default.new.label"
                                                              args="[entityName]"/></g:link></li>
    </ul>
</div>

<div id="list-depositType" class="content scaffold-list" role="main">
    <h1><g:message code="default.list.label" args="[entityName]"/></h1>
    <g:if test="${flash.message}">
        <div class="message" role="status">${flash.message}</div>
    </g:if>
    <table>
        <thead>
        <tr>

            <g:sortableColumn property="alias" title="${message(code: 'depositType.alias.label', default: 'Alias')}"/>

            <g:sortableColumn property="description"
                              title="${message(code: 'depositType.description.label', default: 'Description')}"/>

        </tr>
        </thead>
        <tbody>
        <g:each in="${depositTypeInstanceList}" status="i" var="depositTypeInstance">
            <tr class="${(i % 2) == 0 ? 'even' : 'odd'}">

                <td><g:link action="show"
                            id="${depositTypeInstance.id}">${fieldValue(bean: depositTypeInstance, field: "alias")}</g:link></td>

                <td>${fieldValue(bean: depositTypeInstance, field: "description")}</td>

            </tr>
        </g:each>
        </tbody>
    </table>

    <div class="pagination">
        <g:paginate total="${depositTypeInstanceCount ?: 0}"/>
    </div>
</div>
</body>
</html>

grails-app/views/depositType/show.gsp
<%@ page import="ibs_lab1.DepositType" %>
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="main">
    <g:set var="entityName" value="${message(code: 'depositType.label', default: 'DepositType')}"/>
    <title><g:message code="default.show.label" args="[entityName]"/></title>
</head>

<body>
<a href="#show-depositType" class="skip" tabindex="-1"><g:message code="default.link.skip.label"
                                                                  default="Skip to content&hellip;"/></a>

<div class="nav" role="navigation">
    <ul>
        <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
        <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]"/></g:link></li>
        <li><g:link class="create" action="create"><g:message code="default.new.label"
                                                              args="[entityName]"/></g:link></li>
    </ul>
</div>

<div id="show-depositType" class="content scaffold-show" role="main">
    <h1><g:message code="default.show.label" args="[entityName]"/></h1>
    <g:if test="${flash.message}">
        <div class="message" role="status">${flash.message}</div>
    </g:if>
    <ol class="property-list depositType">

        <g:if test="${depositTypeInstance?.alias}">
            <li class="fieldcontain">
                <span id="alias-label" class="property-label"><g:message code="depositType.alias.label"
                                                                         default="Alias"/></span>

                <span class="property-value" aria-labelledby="alias-label"><g:fieldValue bean="${depositTypeInstance}"
                                                                                         field="alias"/></span>

            </li>
        </g:if>

        <g:if test="${depositTypeInstance?.description}">
            <li class="fieldcontain">
                <span id="description-label" class="property-label"><g:message code="depositType.description.label"
                                                                               default="Description"/></span>

                <span class="property-value" aria-labelledby="description-label"><g:fieldValue
                        bean="${depositTypeInstance}" field="description"/></span>

            </li>
        </g:if>

    </ol>
    <g:form url="[resource: depositTypeInstance, action: 'delete']" method="DELETE">
        <fieldset class="buttons">
            <g:link class="edit" action="edit" resource="${depositTypeInstance}"><g:message
                    code="default.button.edit.label" default="Edit"/></g:link>
            <g:actionSubmit class="delete" action="delete"
                            value="${message(code: 'default.button.delete.label', default: 'Delete')}"
                            onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');"/>
        </fieldset>
    </g:form>
</div>
</body>
</html>